name: Sync Fork

on:
  push: 
  schedule:
    - cron: '0 */6 * * *' # 每6个小时一次
  workflow_dispatch: # 手动触发

env:
  OWNER: deanxv
  HEAD: main
  BASE: main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with upstream
        uses: TG908/fork-sync@v1.2 # 使用最新版本
        continue-on-error: true # 如果这步出错，继续执行后面的步骤
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ env.OWNER }}
          head: ${{ env.HEAD }}
          base: ${{ env.BASE }}
          merge_method: merge
          pr_title: Fork Sync

      - name: Check status
        run: echo "Sync completed"
